# Generated by Django 5.0.1 on 2024-05-04 16:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_codes'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='passport_from',
            field=models.CharField(default='МДВ ПО Г.МОСКВЕ', max_length=100, verbose_name='Кем выдан паспорт'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customuser',
            name='passport_number',
            field=models.CharField(default=0, max_length=4, validators=[django.core.validators.RegexValidator(message='Серия паспорта должна состоять из 6 цифр', regex='^\\d{6}$')], verbose_name='Номер паспорта'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customuser',
            name='passport_registration_address',
            field=models.CharField(default='ул. Хз, д.15, кв.93', max_length=200, verbose_name='Зарегистрирован по адресу'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customuser',
            name='passport_series',
            field=models.CharField(default='0000', max_length=4, validators=[django.core.validators.RegexValidator(message='Серия паспорта должна состоять из 4 цифр', regex='^\\d{4}$')], verbose_name='Серия паспорта'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customuser',
            name='patronymic',
            field=models.CharField(blank=True, default=None, null=True, verbose_name='Отчество'),
        ),
    ]
