# Generated by Django 5.0.1 on 2024-05-11 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_customuser_groups'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='groups',
            field=models.ManyToManyField(related_name='users_roles', to='users.customgroup', verbose_name='Роли'),
        ),
    ]
