# Generated by Django 4.0.1 on 2024-05-12 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        # ('auth', '0016_remove_group_users_guide'),
        ('users', '0009_alter_customuser_groups'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customgroup',
            name='permissions',
            field=models.ManyToManyField(blank=True, to='auth.Permission', verbose_name='Права'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='groups',
            field=models.ManyToManyField(related_name='users_roles', to='users.CustomGroup', verbose_name='Роли'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='patronymic',
            field=models.CharField(blank=True, default=None, max_length=100, null=True, verbose_name='Отчество'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions'),
        ),
    ]
