# Generated by Django 5.0.1 on 2024-05-11 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backupDb', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backup',
            name='name',
            field=models.CharField(max_length=255, verbose_name='backup файл'),
        ),
    ]
