# Generated by Django 5.0.1 on 2024-03-14 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='housing',
            name='tags',
            field=models.ManyToManyField(blank=True, null=True, related_name='housings', to='main.tag', verbose_name='Теги'),
        ),
    ]
