# Generated by Django 5.0.1 on 2024-02-27 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_country_alter_category_options_alter_image_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='country',
            options={'verbose_name': 'Страна', 'verbose_name_plural': 'Страны'},
        ),
        migrations.AlterField(
            model_name='housing',
            name='short_name',
            field=models.CharField(blank=True, null=True, verbose_name='Сокращенное название'),
        ),
    ]
