# Generated by Django 5.0.1 on 2024-03-19 10:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_publishedhousing_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='housing',
            name='images',
            field=models.ManyToManyField(related_name='housing', through='main.HousingImages', to='main.image', verbose_name='Изображения'),
        ),
        migrations.AlterField(
            model_name='housingimages',
            name='housing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.housing', verbose_name='Жилье'),
        ),
    ]
