# Generated by Django 5.0.1 on 2024-03-19 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='currency',
            name='name',
            field=models.CharField(default=1, unique=True, verbose_name='Название'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='currency',
            name='publish_name',
            field=models.CharField(default=1, max_length=5, verbose_name='Сокращенное название'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='currency',
            name='code',
            field=models.CharField(max_length=4, unique=True, verbose_name='Кодовое название'),
        ),
    ]
