# Generated by Django 5.0.1 on 2024-03-19 19:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_currency_name_currency_publish_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='publishedhousing',
            name='currency',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='main.currency', verbose_name='Валюту'),
            preserve_default=False,
        ),
    ]
