# Generated by Django 5.0.1 on 2024-04-03 21:51

import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_cartitem_unique_cart_item'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Отзыв'),
        ),
        migrations.AlterField(
            model_name='housing',
            name='address',
            field=models.CharField(default=django.utils.timezone.now, verbose_name='Адрес'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='housing',
            name='number_of_seats',
            field=models.PositiveIntegerField(default=1, verbose_name='Количество мест'),
        ),
        migrations.AlterUniqueTogether(
            name='feedback',
            unique_together={('product', 'user')},
        ),
    ]
