# Generated by Django 5.0.1 on 2024-04-23 08:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_alter_feedback_description_alter_housing_address_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Город')),
            ],
            options={
                'verbose_name': 'Город',
                'verbose_name_plural': 'Города',
            },
        ),
        migrations.RemoveField(
            model_name='housing',
            name='country',
        ),
        migrations.RemoveField(
            model_name='housing',
            name='types',
        ),
        migrations.AlterModelOptions(
            name='feedback',
            options={'ordering': ['-date_push'], 'verbose_name': 'Отзыв', 'verbose_name_plural': 'Отзывы'},
        ),
        migrations.AddField(
            model_name='housing',
            name='city',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='housings', to='main.city', verbose_name='Город'),
        ),
        migrations.CreateModel(
            name='Metro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(unique=True, verbose_name='Метро')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.city', verbose_name='Город')),
            ],
            options={
                'verbose_name': 'Метро',
                'verbose_name_plural': 'Метро',
            },
        ),
        migrations.AddField(
            model_name='housing',
            name='metro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='main.metro', verbose_name='Метро'),
        ),
        migrations.DeleteModel(
            name='Country',
        ),
        migrations.DeleteModel(
            name='TypeHousing',
        ),
    ]
