# Generated by Django 5.0.1 on 2024-04-23 08:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_district_alter_city_options_remove_housing_city_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='city',
            options={'verbose_name': 'Город', 'verbose_name_plural': 'Города'},
        ),
        migrations.AlterModelOptions(
            name='district',
            options={'verbose_name': 'Округ', 'verbose_name_plural': 'Округа'},
        ),
        migrations.AlterField(
            model_name='housing',
            name='district',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='housings', to='main.district', verbose_name='Округ'),
            preserve_default=False,
        ),
    ]
