# Generated by Django 5.0.1 on 2024-04-25 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_alter_city_options_alter_district_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PublicationStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Статус публикации')),
            ],
            options={
                'verbose_name': 'Статус публикации',
                'verbose_name_plural': 'Статусы публикации',
            },
        ),
    ]
