# Generated by Django 5.0.1 on 2024-04-25 11:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_publicationstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='publishedhousing',
            name='status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='main.publicationstatus', verbose_name='Статус публикации'),
            preserve_default=False,
        ),
    ]
