# Generated by Django 5.0.1 on 2024-05-04 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_alter_messagesrequest_options_buyrequest_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyrequest',
            name='buyer_confirm',
            field=models.BooleanField(default=True, verbose_name='Подтверждение покупателя'),
        ),
        migrations.AddField(
            model_name='buyrequest',
            name='contract',
            field=models.FileField(blank=True, null=True, upload_to='contracts/% Y/% m/% d/', verbose_name='Договор'),
        ),
        migrations.AddField(
            model_name='buyrequest',
            name='owner_confirm',
            field=models.BooleanField(default=False, verbose_name='Подтверждение хозяина'),
        ),
    ]
