# Generated by Django 5.0.1 on 2024-05-04 17:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_alter_buyrequest_product_alter_buyrequest_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='housing',
            name='city',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='housings', to='main.city', verbose_name='Город'),
            preserve_default=False,
        ),
    ]
