# Generated by Django 5.0.1 on 2024-05-05 17:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_remove_buyrequest_unique_cart_item_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='buyrequest',
            name='is_buy',
            field=models.BooleanField(default=False, verbose_name='Статус оплаты'),
        ),
        migrations.AlterUniqueTogether(
            name='buyrequest',
            unique_together={('product', 'user')},
        ),
    ]
