# Generated by Django 5.0.1 on 2024-05-06 01:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_buyrequest_is_buy_alter_buyrequest_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publishedhousing',
            name='status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='main.publicationstatus', verbose_name='Статус публикации'),
        ),
    ]
