# Generated by Django 5.0.1 on 2024-05-11 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_alter_publishedhousing_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='housing',
            name='tags',
            field=models.ManyToManyField(related_name='housings', to='main.tag', verbose_name='Теги'),
        ),
    ]
