# Generated by Django 4.0.1 on 2024-05-12 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0028_alter_housing_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currency',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='housing',
            name='address',
            field=models.CharField(max_length=255, verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='housing',
            name='categories',
            field=models.ManyToManyField(related_name='housings', to='main.Category', verbose_name='Категории'),
        ),
        migrations.AlterField(
            model_name='housing',
            name='images',
            field=models.ManyToManyField(related_name='housing', through='main.HousingImages', to='main.Image', verbose_name='Изображения'),
        ),
        migrations.AlterField(
            model_name='housing',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='Название жилья'),
        ),
        migrations.AlterField(
            model_name='housing',
            name='short_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Сокращенное название'),
        ),
        migrations.AlterField(
            model_name='housing',
            name='tags',
            field=models.ManyToManyField(related_name='housings', to='main.Tag', verbose_name='Теги'),
        ),
        migrations.AlterField(
            model_name='metro',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Метро'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name='Название тега'),
        ),
    ]
