# Generated by Django 5.0.1 on 2024-05-12 18:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0029_alter_currency_name_alter_housing_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='housing',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='housings', to='main.city', verbose_name='Город'),
        ),
    ]
