name: ApiDjangoCheck

on: [push, pull_request]

jobs:
  check-style-python:
    runs-on: ubuntu-latest
    steps:
    - name: Git_clone_project
      uses: actions/checkout@v2

    - name: Set_version_python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'

    - name: Install_project_dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Flake8
      run: |
        flake8

    - name: CheckStyle
        run: |
          pip install pycodestyle
          pycodestyle .