name: ApiDjangoCheck

on: [push, pull_request]

jobs:
  check-style-python:
    runs-on: ubuntu-latest
    steps:
    - name: Git_clone_project
      uses: actions/checkout@v2

    - name: Set_version_python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'

    - name: Install_project_dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: RunFlake8
      run: |
        pip install flake8
        flake8 main/serializers.py

    - name: CheckStyle
      run: |
        pip install pycodestyle
        pycodestyle .
